/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutPurchaseIntentIdRouteImport } from './routes/checkout.$purchaseIntentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPurchaseIntentIdRoute =
  CheckoutPurchaseIntentIdRouteImport.update({
    id: '/checkout/$purchaseIntentId',
    path: '/checkout/$purchaseIntentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout/$purchaseIntentId': typeof CheckoutPurchaseIntentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout/$purchaseIntentId': typeof CheckoutPurchaseIntentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout/$purchaseIntentId': typeof CheckoutPurchaseIntentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checkout/$purchaseIntentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkout/$purchaseIntentId'
  id: '__root__' | '/' | '/checkout/$purchaseIntentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutPurchaseIntentIdRoute: typeof CheckoutPurchaseIntentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$purchaseIntentId': {
      id: '/checkout/$purchaseIntentId'
      path: '/checkout/$purchaseIntentId'
      fullPath: '/checkout/$purchaseIntentId'
      preLoaderRoute: typeof CheckoutPurchaseIntentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutPurchaseIntentIdRoute: CheckoutPurchaseIntentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
